# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af128356a19624b70cdd4a705e62da2e8511d00ec5d9cede6c5e99b6eb66b32b41e277edcd5b170358ea699b1d7cb9459d7205cd3ce4f427aea816d92b473fbc

test:
  secret_key_base: 448c6c1b45eec95bfbe930955be94e5c585d0c91fa75d9dfb39620b901e83bce57ff45a308041e1ca41409e29c07421307e9ca932b40337e980e5764b7f5afef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
